---
- name: web server
  hosts: localhost
  sudo: True
  vars:
    site_prefix: "{{ ansible_local.site.info.prefix }}"
  tasks:
   - name: include ssh keys
     include_vars: ssh-vars.yml
   - name: install nginx
     apt: name=nginx update_cache=yes
   - name: install git
     apt: name=git
   - name: checkout nginx config
     git: repo=git://github.com/idguk/nginx.git dest=/tmp/nginx/ update=yes accept_hostkey=yes
   - name: update nginx config
     copy: src=/tmp/nginx/nginx.conf dest=/etc/nginx/nginx.conf
#docker-py needed for docker client
   - name: install docker py
     pip: name=docker-py
   - name: checkout shared
     git: repo=git://github.com/idguk/shared-coldfusion.git dest=/var/www/sharedresources/ update=yes accept_hostkey=yes
   - name: checkout site
     git: repo=git@bitbucket.org:idguk/site-{{site_prefix}}.git dest=/var/www/{{site_prefix}}/ update=yes accept_hostkey=yes
   - name: copy nginx conf
     copy: src=/var/www/{{site_prefix}}/nginx.conf dest=/etc/nginx/conf.d/{{site_prefix}}.conf 
   - name: restart nginx
     service: name=nginx state=restarted
   - name: railo docker
     docker:
       name: railo 
       image: idguk/railoexpress
       pull: always
       ports: "8888:8888"
       state: started
        #expose:
        #- 8888
       volumes:
          - "/var/www/{{site_prefix}}:/var/railo/webapps/ROOT" 
          - "/var/www/sharedresources/:/var/railo/webapps/sharedresources/"
