---
- name: web server
  hosts: localhost
  sudo: True
  vars:
    site_prefix: "{{ ansible_local.site.info.prefix }}"
    public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1p0hgen9BjMQk6g0jAeeMUC1+TPpgk0zvuiQnkhklZ/tB+iF2wKenNMnw7YAVeHhnRtSa3q2W
PhzgdDzEbEVbUHFAK8ZAaV0DzcbN9FE2XL3cvTR8DHfu/xWcuMBZ7l7ArIWc5lvX/RwwlvlLPr+cW6uslTJpjB6pP0OCizoBe4GBaXsVk7oNq0iF
m83KJ6aqETslgpWsFf+E4XuJS19e6D7VZRg3nTbB5rpkA0Jn592azfCee8UUoYjDFeiA6wbRSQmDtdGOQB7SVQldx5VWEN8PR4yul4Lp6HbUW5Nj
6LBFoR9OTSr7c/5ngltDOwGYwwL6cGdl+bxQwpfIJ36N root@pca-grp-l7vu"
    privater_key: "-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAtadIYHp/QYzEJOoNIwHnjFAtfkz6YJNM77okJ5IZJWf7Qfoh
dsCnpzTJ8O2AFXh4Z0bUmt6tlj4c4HQ8xGxFW1BxQCvGQGldA83GzfRRNly93L00
fAx37v8VnLjAWe5ewKyFnOZb1/0cMJb5Sz6/nFurrJUyaYweqT9Dgos6AXuBgWl7
FZO6DatIhZvNyiemqhE7JYKVrBX/hOF7iUtfXug+1WUYN502wea6ZANCZ+fdms3w
nnvFFKGIwxXogOsG0UkJg7XRjkAe0lUJXceVVhDfD0eMrpeC6eh21FuTY+iwRaEf
Tk0q+3P+Z4JbQzsBmMMC+nBnZfm8UMKXyCd+jQIDAQABAoIBADcRFfzBRbB+VruG
BCN3oVTEvXXLKh96p9kISYuBW4QeaGmQxPI15tzmQM17gdeAZKeSLkMge+jOvXxB
YGZ/F+tdkGdOndPK3PqZN8oZZUEgjiHLbYypTvYxd8DBtPXOMAUih4KPxonMXe5Q
5hOsWvOwSnOP6u9aHbVay0FYqWXnIxSdIyJW01FJoga/99Rr7cbnnxMb+L7LVauC
3pJD7FUsa511OTOqeBW14s3zs56u6t8dUQbaRt69/SIVmPPpCQTBGrlOrYYJin/w
KLYHR4IVZVsOuY0Ithux1NWJPxeLPp3AeyaNs1gdFxTMJH4k0D4hECfRYM+ceBD5
YxbF2xUCgYEA2UQFL9k2tHZmHdxKjRbIB7JayJw6afZg77C1hl8FA085FR1HrlPg
m3PcIlS/OCj2FwhbDqAryieXytJFnArfOMDFBMfjJNaq5hlfjerCLxxI0m75Cchh
SBaeHouA4K4hxbQkwyU76LWpHuAA6JA9lE/LaL47rw4UvvZArFAVC7sCgYEA1gns
a+uvw+k8l/c8uzMtSXKL/UReX+mpTdl/2vd/tMPeNhqaMK22FvdslUCtBnclF5wZ
BCNoCpTwvs2WcQLjCRi46HhV3bZRu3eonFgTxdiCNAZY8N5s7X47lXykDf639DTz
z8U31wcFS1u0Tdr1GQa3yfPR9MBoHlxooyO8ZlcCgYBGXUI0yeturL3Lw/GdGhi0
bW37dKVydenVFuzjVNjBxqGdFfuGGQIwNmi/8aRwYsu4j+s1pGgqM4J0nH8Q13CN
59inALmuz5tPpD4PL02uhkGLbYdYRL5E45ZYHCQkICEt73bMgL2TU2ovZqrEpxpa
czFUfe/EdRIA+q3dYJ5ASwKBgCAtBbmDiLyux0khBaQuoVQ1QA4mxPkuKyFk3O+R
3UTTXQhNH3jJ5GG3eD9HpbsfFhhigvA4Ul+k3DwSs9bxVCf9624nCOF3kvnXlyVJ
qE9JqOkhOyWaik15eIOUZSUlcYnom+5T+3z7tTQK6SP7EnVcqSxW1u0wL3bA9Ynw
yVWpAoGBANgiWogY5O0K0nauFSPUHmwCGaiuLBjhFkemIiOKFauNFm5wsXjiYZpy
TY0Rg7qQTXQu3HYoZjezQj+61+nZ1czLHec6PDu+dGrqLdwLiD15lTnnKyrcXKbE
RhYiXKD5iiLJqvQquHAcS0hoNTaCW95q6fcVpLMTCxBd0CZ9L+BX
-----END RSA PRIVATE KEY-----"
  tasks:
   - name: install nginx
     apt: name=nginx update_cache=yes
   - name: install git
     apt: name=git
   - name: checkout nginx config
     git: repo=git://github.com/idguk/nginx.git dest=/tmp/nginx/ update=yes accept_hostkey=yes
   - name: update nginx config
     copy: src=/tmp/nginx/nginx.conf dest=/etc/nginx/nginx.conf
#docker-py needed for docker client
   - name: install docker py
     pip: name=docker-py
   - name: checkout shared
     git: repo=git://github.com/idguk/shared-coldfusion.git dest=/var/www/sharedresources/ update=yes accept_hostkey=yes
   - name: checkout site
     git: repo=git://github.com/idguk/site-{{site_prefix}} dest=/var/www/{{site_prefix}}/ update=yes accept_hostkey=yes
   - name: copy nginx conf
     copy: src=/var/www/{{site_prefix}}/nginx.conf dest=/etc/nginx/conf.d/{{site_prefix}}.conf 
   - name: restart nginx
     service: name=nginx state=restarted
   - name: railo docker
     docker:
       name: railo 
       image: idguk/railoexpress
       pull: always
       ports: "8888:8888"
       state: started
        #expose:
        #- 8888
       volumes:
          - "/var/www/{{site_prefix}}:/var/railo/webapps/ROOT" 
          - "/var/www/sharedresources/:/var/railo/webapps/sharedresources/"
